# CORS Security Configuration Values
# This file provides the enhanced values for the Traefik middleware configuration
# Add these values to your main values.yaml file or include as a separate values file

traefik:
  enabled: true
  
  # Enhanced OPTIONS route configuration
  optionsRoute:
    priority: 150  # Higher than default routes
    fallback:
      enabled: true
      pathPrefix: "/api"
      priority: 140
  
  middleware:
    # Enhanced OPTIONS-specific rate limiting
    optionsRateLimit:
      enhanced:
        # Security review recommended: 20 req/sec (1200/min)
        average: 1200  # requests per minute
        period: "1m"
        burst: 300     # burst capacity
        depth: 2       # X-Forwarded-For depth for real IP detection
        trustedIPs:    # Additional trusted IP ranges (customize for your environment)
          - "203.0.113.0/24"  # Example: office network
          # Add your CDN/proxy IPs here
    
    # Enhanced CORS configuration
    cors:
      enabled: true
      enhanced:
        # Production should use strict origins, development can be more permissive
        strictOrigins: false  # set to true in production
        allowOrigins:
          # Production origins (customize for your domains)
          - "https://app.tresor.vn"
          - "https://pvpipe.tresor.vn"
          - "https://admin.tresor.vn"
        allowOriginRegex:
          # Development patterns
          - "^https?://localhost(:[0-9]+)?$"
          - "^https?://127\\.0\\.0\\.1(:[0-9]+)?$"
          - "^https://.*\\.tresor\\.vn$"
          - "^https://.*\\.pvpipe\\.com$"
        additionalHeaders:
          - "X-File-Name"
          - "X-API-Version"
          - "X-Request-ID"
        maxAge: 86400  # 24 hours for preflight cache
        allowCredentials: false  # Set to true if cookies needed
    
    # Security monitoring configuration
    optionsMonitoring:
      enabled: true  # Enable advanced logging for security analysis

# CORS Handler Service Configuration
services:
  corsHandler:
    enabled: true
    replicas: 2
    port: 8080
    
    # Container image configuration
    image:
      repository: "nginx"  # Replace with your CORS handler image
      tag: "alpine"
      pullPolicy: "IfNotPresent"
    
    # Resource limits for security and performance
    resources:
      limits:
        cpu: "100m"
        memory: "64Mi"
      requests:
        cpu: "50m"
        memory: "32Mi"
    
    # Health check configuration
    healthCheck:
      enabled: true
      path: "/health"
      readinessPath: "/ready"
      initialDelaySeconds: 10
      periodSeconds: 30
      readinessPeriodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
      readinessFailureThreshold: 3
      startupInitialDelaySeconds: 5
      startupPeriodSeconds: 5
      startupFailureThreshold: 10
    
    # Security configuration
    securityHeaders:
      enabled: true
    
    # Environment variables
    env:
      - name: "ENVIRONMENT"
        value: "production"  # or "development"
    
    # Service configuration
    service:
      type: "ClusterIP"
      annotations: {}
    
    # Service account configuration
    serviceAccount:
      automountToken: false  # Security best practice
    
    # Pod Disruption Budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    
    # Horizontal Pod Autoscaler
    horizontalPodAutoscaler:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCpuUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 50
              periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60
          policies:
            - type: Percent
              value: 100
              periodSeconds: 60

# Network Policy (if using network policies)
networkPolicy:
  corsHandler:
    enabled: true
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/name: traefik
        ports:
          - protocol: TCP
            port: 8080