{{- if and .Values.traefik.enabled .Values.services.corsHandler.enabled }}
---
# CORS Handler Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvpipe.fullname" . }}-cors-handler
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
  annotations:
    security.pvpipe.io/purpose: "Service for lightweight CORS preflight handler"
    {{- if .Values.services.corsHandler.service.annotations }}
    {{- toYaml .Values.services.corsHandler.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.services.corsHandler.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.services.corsHandler.port | default 8080 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "pvpipe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
  # Session affinity not needed for stateless CORS handler
  sessionAffinity: None
  {{- if .Values.services.corsHandler.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.services.corsHandler.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.services.corsHandler.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.services.corsHandler.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}

---
# Service Account for CORS Handler
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pvpipe.serviceAccountName" . }}-cors-handler
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
  annotations:
    security.pvpipe.io/purpose: "Minimal service account for CORS handler"
automountServiceAccountToken: {{ .Values.services.corsHandler.serviceAccount.automountToken | default false }}

{{- if .Values.services.corsHandler.podDisruptionBudget.enabled }}
---
# Pod Disruption Budget for CORS Handler
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pvpipe.fullname" . }}-cors-handler
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
spec:
  {{- if .Values.services.corsHandler.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.services.corsHandler.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.services.corsHandler.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.services.corsHandler.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cors-handler
{{- end }}

{{- if .Values.services.corsHandler.horizontalPodAutoscaler.enabled }}
---
# Horizontal Pod Autoscaler for CORS Handler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pvpipe.fullname" . }}-cors-handler
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pvpipe.fullname" . }}-cors-handler
  minReplicas: {{ .Values.services.corsHandler.horizontalPodAutoscaler.minReplicas | default 2 }}
  maxReplicas: {{ .Values.services.corsHandler.horizontalPodAutoscaler.maxReplicas | default 10 }}
  metrics:
    {{- if .Values.services.corsHandler.horizontalPodAutoscaler.targetCpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.corsHandler.horizontalPodAutoscaler.targetCpuUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.corsHandler.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.corsHandler.horizontalPodAutoscaler.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.services.corsHandler.horizontalPodAutoscaler.behavior }}
  behavior:
    {{- toYaml .Values.services.corsHandler.horizontalPodAutoscaler.behavior | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}