{{- if and .Values.traefik.enabled .Values.traefik.middleware.forwardAuth.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "pvpipe.fullname" . }}-forward-auth
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: traefik-middleware
spec:
  forwardAuth:
    address: http://{{ .Release.Name }}-ms-auth:{{ .Values.msAuth.servicePort }}/internal/verify
    trustForwardHeader: true
    authResponseHeaders:
      - X-User-Id
      - X-Employee-Id
      - X-Department-Id
      - X-User-Email
      - X-User-Role
      - X-User-Permissions
      - X-User-Is-Super-Admin
    authRequestHeaders:
      - Authorization
      - X-Forwarded-Method
      - X-Forwarded-Uri
      - X-Forwarded-Host
{{- end }}