{{- if .Values.traefik.enabled }}
---
# Main API Gateway IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-api-gateway
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  entryPoints:
    - web
  routes:
    {{- range $name, $route := .Values.traefik.routes }}
    {{- if $route.enabled }}
    - match: PathPrefix(`{{ $route.pathPrefix }}`)
      kind: Rule
      {{- if eq $route.pathPrefix "/" }}
      priority: 1
      {{- else }}
      priority: 10
      {{- end }}
      services:
        - name: {{ tpl $route.service $ }}
          port: {{ $route.port }}
      {{- if or $route.middlewares (and $route.protected $.Values.traefik.middleware.jwt.enabled) }}
      middlewares:
        {{- if and $route.protected $.Values.traefik.middleware.jwt.enabled }}
        - name: {{ include "pvpipe.fullname" $ }}-jwt-auth
        {{- end }}
        {{- if $route.middlewares }}
        {{- range $route.middlewares }}
        - name: {{ include "pvpipe.fullname" $ }}-{{ . }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}