{{- if .Values.traefik.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pvpipe.fullname" . }}-api-gateway
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.traefik.ingress.annotations }}
    {{- toYaml .Values.traefik.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.traefik.ingress.className }}
  ingressClassName: {{ .Values.traefik.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.traefik.apiGateway.host }}
      secretName: domain-tls-secret
  rules:
    - host: {{ .Values.traefik.apiGateway.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-traefik
                port:
                  number: 80
{{- end }}