{{- if .Values.traefik.enabled }}
---
# Main API Gateway IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-api-gateway
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  entryPoints:
    - web
  routes:
    {{- range $name, $route := .Values.traefik.routes }}
    {{- if $route.enabled }}
    # OPTIONS requests bypass forward auth
    - match: {{ if $route.useRegex }}Method(`OPTIONS`) && PathRegexp(`{{ $route.pathPrefix }}`){{ else }}Method(`OPTIONS`) && PathPrefix(`{{ $route.pathPrefix }}`){{ end }}
      kind: Rule
      {{- if eq $route.pathPrefix "/" }}
      priority: 2
      {{- else }}
      priority: 11
      {{- end }}
      services:
        - name: {{ tpl $route.service $ }}
          port: {{ $route.port }}
      {{- if $route.middlewares }}
      middlewares:
        {{- range $route.middlewares }}
        - name: {{ include "pvpipe.fullname" $ }}-{{ . }}
        {{- end }}
      {{- end }}
    # All other methods go through normal flow
    - match: {{ if $route.useRegex }}!Method(`OPTIONS`) && PathRegexp(`{{ $route.pathPrefix }}`){{ else }}!Method(`OPTIONS`) && PathPrefix(`{{ $route.pathPrefix }}`){{ end }}
      kind: Rule
      {{- if eq $route.pathPrefix "/" }}
      priority: 1
      {{- else }}
      priority: 10
      {{- end }}
      services:
        - name: {{ tpl $route.service $ }}
          port: {{ $route.port }}
      {{- if or $route.middlewares (and $route.protected $.Values.traefik.middleware.forwardAuth.enabled) }}
      middlewares:
        {{- if and $route.protected $.Values.traefik.middleware.forwardAuth.enabled }}
        - name: {{ include "pvpipe.fullname" $ }}-forward-auth
        {{- end }}
        {{- if $route.middlewares }}
        {{- range $route.middlewares }}
        - name: {{ include "pvpipe.fullname" $ }}-{{ . }}
        {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}