{{- if .Values.traefik.enabled }}
---
# Main API Gateway IngressRoute
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-api-gateway
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
spec:
  entryPoints:
    - web
  routes:
    {{- range $name, $route := .Values.traefik.routes }}
    {{- if $route.enabled }}
    {{- if ne $name "root" }}
    - match: Host(`{{ $.Values.traefik.apiGateway.host }}`) && PathPrefix(`{{ $route.pathPrefix }}`)
      kind: Rule
      priority: 100
      services:
        - name: {{ tpl $route.service $ }}
          port: {{ $route.port }}
      {{- if $route.middlewares }}
      middlewares:
        {{- range $route.middlewares }}
        - name: {{ include "pvpipe.fullname" $ }}-{{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- range $name, $route := .Values.traefik.routes }}
    {{- if and $route.enabled (eq $name "root") }}
    # Catch-all route for any host
    - match: PathPrefix(`{{ $route.pathPrefix }}`)
      kind: Rule
      priority: 1
      services:
        - name: {{ tpl $route.service $ }}
          port: {{ $route.port }}
      {{- if $route.middlewares }}
      middlewares:
        {{- range $route.middlewares }}
        - name: {{ include "pvpipe.fullname" $ }}-{{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
{{- end }}