{{- if and .Values.traefik.enabled .Values.traefik.middleware.jwt.enabled (not .Values.traefik.middleware.jwt.secret.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pvpipe.fullname" . }}-jwt-secret
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: jwt-secret
type: Opaque
stringData:
  {{- if .Values.env.JWT_SECRET }}
  # Use JWT_SECRET from env (same as backend)
  {{ .Values.traefik.middleware.jwt.secret.key | default "jwt-secret" }}: {{ .Values.env.JWT_SECRET | quote }}
  {{- else if .Values.traefik.middleware.jwt.secret.value }}
  # Use explicitly provided secret value
  {{ .Values.traefik.middleware.jwt.secret.key | default "jwt-secret" }}: {{ .Values.traefik.middleware.jwt.secret.value | quote }}
  {{- else }}
  {{- fail "JWT_SECRET must be provided either via env.JWT_SECRET or traefik.middleware.jwt.secret.value" }}
  {{- end }}
{{- end }}