{{- if and .Values.traefik.enabled false }}
---
# OPTIONS Preflight Bypass IngressRoute - HIGHEST PRIORITY
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-options-bypass
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway-options
  annotations:
    # Security annotation to document the purpose
    security.pvpipe.io/purpose: "CORS preflight bypass - OPTIONS method only"
    security.pvpipe.io/risk-level: "low"
    security.pvpipe.io/reviewer: "api-architect"
spec:
  entryPoints:
    - web
    {{- if .Values.traefik.tls.enabled }}
    - websecure
    {{- end }}
  routes:
    # OPTIONS bypass route with highest priority (100+)
    - match: Method(`OPTIONS`)
      kind: Rule
      priority: 100
      services:
        # Route OPTIONS to a lightweight CORS handler service
        - name: {{ include "pvpipe.fullname" . }}-cors-handler
          port: 8080
      middlewares:
        # Apply CORS middleware but NOT forward-auth
        - name: {{ include "pvpipe.fullname" . }}-cors
        - name: {{ include "pvpipe.fullname" . }}-security-headers
        - name: {{ include "pvpipe.fullname" . }}-rate-limit-options
        {{- if .Values.traefik.middleware.logging.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-options-logging
        {{- end }}
  {{- if .Values.traefik.tls.enabled }}
  tls:
    {{- toYaml .Values.traefik.tls | nindent 4 }}
  {{- end }}
{{- end }}