{{- if and .Values.traefik.enabled false }}
---
# Enhanced OPTIONS Preflight Bypass IngressRoute - HIGHEST PRIORITY
# Security review implemented: 2025-08-02
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-options-bypass-enhanced
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway-options-enhanced
  annotations:
    # Security annotations documenting the enhanced implementation
    security.pvpipe.io/purpose: "Enhanced CORS preflight bypass - OPTIONS method only"
    security.pvpipe.io/risk-level: "low"
    security.pvpipe.io/reviewer: "backend-developer"
    security.pvpipe.io/review-date: "2025-08-02"
    security.pvpipe.io/features: "graduated-rate-limiting,origin-validation,method-override-protection"
    security.pvpipe.io/monitoring: "enabled"
spec:
  entryPoints:
    - web
    {{- if .Values.traefik.tls.enabled }}
    - websecure
    {{- end }}
  routes:
    # Enhanced OPTIONS bypass route with highest priority
    - match: Method(`OPTIONS`)
      kind: Rule
      priority: {{ .Values.traefik.optionsRoute.priority | default 150 }}
      services:
        # Route OPTIONS to enhanced CORS handler service
        - name: {{ include "pvpipe.fullname" . }}-cors-handler
          port: {{ .Values.services.corsHandler.port | default 8080 }}
          # Health check configuration for CORS handler
          {{- if .Values.services.corsHandler.healthCheck.enabled }}
          healthCheck:
            path: {{ .Values.services.corsHandler.healthCheck.path | default "/health" }}
            interval: {{ .Values.services.corsHandler.healthCheck.interval | default "30s" }}
            timeout: {{ .Values.services.corsHandler.healthCheck.timeout | default "3s" }}
          {{- end }}
      middlewares:
        # Enhanced middleware chain for security
        # 1. Rate limiting with graduated enforcement
        - name: {{ include "pvpipe.fullname" . }}-rate-limit-options-enhanced
        # 2. Origin validation and method override protection
        - name: {{ include "pvpipe.fullname" . }}-origin-validation
        # 3. Enhanced CORS handling (without forward-auth)
        - name: {{ include "pvpipe.fullname" . }}-cors-enhanced
        # 4. Security monitoring
        - name: {{ include "pvpipe.fullname" . }}-options-security-monitoring
        {{- if .Values.traefik.middleware.optionsMonitoring.enabled }}
        # 5. Advanced logging for security analysis
        - name: {{ include "pvpipe.fullname" . }}-options-advanced-logging
        {{- end }}
        {{- if .Values.traefik.middleware.compress.enabled }}
        # 6. Compression (minimal for OPTIONS responses)
        - name: {{ include "pvpipe.fullname" . }}-compress
        {{- end }}

    {{- if .Values.traefik.optionsRoute.fallback.enabled }}
    # Fallback route for non-standard OPTIONS patterns
    - match: Method(`OPTIONS`) && PathPrefix(`{{ .Values.traefik.optionsRoute.fallback.pathPrefix | default "/api" }}`)
      kind: Rule
      priority: {{ .Values.traefik.optionsRoute.fallback.priority | default 140 }}
      services:
        - name: {{ include "pvpipe.fullname" . }}-cors-handler
          port: {{ .Values.services.corsHandler.port | default 8080 }}
      middlewares:
        # Same enhanced middleware chain
        - name: {{ include "pvpipe.fullname" . }}-rate-limit-options-enhanced
        - name: {{ include "pvpipe.fullname" . }}-origin-validation  
        - name: {{ include "pvpipe.fullname" . }}-cors-enhanced
        - name: {{ include "pvpipe.fullname" . }}-options-security-monitoring
        {{- if .Values.traefik.middleware.optionsMonitoring.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-options-advanced-logging
        {{- end }}
    {{- end }}

  {{- if .Values.traefik.tls.enabled }}
  tls:
    {{- if .Values.traefik.tls.secretName }}
    secretName: {{ .Values.traefik.tls.secretName }}
    {{- end }}
    {{- if .Values.traefik.tls.domains }}
    domains:
      {{- toYaml .Values.traefik.tls.domains | nindent 6 }}
    {{- end }}
    {{- if .Values.traefik.tls.options }}
    options:
      name: {{ .Values.traefik.tls.options }}
    {{- end }}
  {{- end }}
{{- end }}