{{- if .Values.traefik.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pvpipe.fullname" . }}-traefik
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: traefik
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - traefik.io
      - traefik.containo.us
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
      - serverstransporttcps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pvpipe.fullname" . }}-traefik
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pvpipe.fullname" . }}-traefik
subjects:
  - kind: ServiceAccount
    name: {{ include "pvpipe.fullname" . }}-traefik
    namespace: {{ .Release.Namespace }}
{{- end }}