{{- if .Values.msQuoc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-quoc
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-quoc
spec:
  replicas: {{ .Values.msQuoc.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ms-quoc
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ms-quoc
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: ms-quoc
          image: "{{ .Values.msQuoc.image.repository }}:{{ .Values.msQuoc.image.tag }}"
          imagePullPolicy: {{ .Values.msQuoc.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.msQuoc.containerPort | default 8080 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-common-env
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.msQuoc.env.SPRING_PROFILES_ACTIVE | default "production" | quote }}
            - name: SERVER_PORT
              value: {{ .Values.msQuoc.containerPort | default 8080 | quote }}
            {{- if .Values.msQuoc.useReadOnlyDatabase }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL_READONLY
            {{- end }}
            {{- range $key, $value := .Values.msQuoc.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.msQuoc.resources }}
          resources:
            {{- toYaml .Values.msQuoc.resources | nindent 12 }}
          {{- end }}
{{- end }}