{{- if .Values.msQuoc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-quoc
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-quoc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.msQuoc.servicePort | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pvpipe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ms-quoc
{{- end }}