apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- if contains "SECRET" $key }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
