{{- if .Values.gotenberg.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gotenberg
spec:
  selector:
    app: {{ .Release.Name }}-gotenberg
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
{{- end }}
