{{- if .Values.msSearchService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-search-service
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-search-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.msSearchService.servicePort }}
      targetPort: {{ .Values.msSearchService.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pvpipe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ms-search-service
{{- end }}