# Main application
backend:
  enabled: true

replicaCount: 1

image:
  repository: 533267304975.dkr.ecr.ap-southeast-1.amazonaws.com/tresor/pvpipe-backend
  tag: latest
  pullPolicy: Always
  pullSecrets: aws-registry
  annotations: {}

# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: alpine
  storage:
    size: 500M

# VNPTSignPDF
vnptsignpdf:
  enabled: true
  image:
    repository: luuhai48/vnptsignpdf
    tag: latest
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
# LocalSignPDF
localsignpdf:
  enabled: true
  image:
    repository: luuhai48/vnptsignpdf
    tag: latest
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
# Gotenberg
gotenberg:
  enabled: true
  image:
    repository: gotenberg/gotenberg
    tag: 8
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
# Postgres Backup
postgresBackup:
  enabled: true
  image:
    repository: eeshugerman/postgres-backup-s3
    tag: "16"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
# Meilisearch
meilisearch:
  enabled: true
  image:
    repository: getmeili/meilisearch
    tag: v1.11.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 7700
  environment: production
  masterKey: ""  # Set a master key for production use
  dbPath: /meili_data
  persistence:
    enabled: true
    size: 1Gi
    mountPath: /meili_data
    storageClass: ""  # Leave empty to use default storage class
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
# Traefik API Gateway
traefik:
  enabled: true
  # Traefik chart values
  service:
    type: ClusterIP
  ports:
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 80
      protocol: TCP
  ingressRoute:
    dashboard:
      enabled: true
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: false
    kubernetesIngress:
      enabled: false
  logs:
    general:
      level: INFO
    access:
      enabled: true
  metrics:
    prometheus:
      enabled: true
  # API Gateway configuration
  apiGateway:
    host: api.tresor.vn
  # Ingress configuration for API Gateway
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: cluster-issuer-tresor.vn
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      external-dns.alpha.kubernetes.io/hostname: "ingress.tresor.vn"
    tls: []
  # Microservices routing configuration
  routes:
    # Root catch-all route
    root:
      enabled: true
      pathPrefix: /
      stripPrefix: false
      service: "{{ .Release.Name }}-backend"
      port: 8000
      protected: false
      middlewares:
        - rate-limit
        - headers
        - retry
        - compress
    # Example microservice routes (disabled by default)
    docs:
      enabled: false
      pathPrefix: /api/docs
      stripPrefix: true
      service: "{{ .Release.Name }}-docs"
      port: 3000
      protected: false  # Public documentation
      middlewares:
        - rate-limit
        - headers
        - compress
    users:
      enabled: false
      pathPrefix: /api/v1/users
      stripPrefix: true
      service: "{{ .Release.Name }}-users"
      port: 8080
      protected: true  # Requires JWT authentication
      middlewares:
        - rate-limit
        - headers
        - retry
        - compress
    auth:
      enabled: false
      pathPrefix: /api/auth
      stripPrefix: true
      service: "{{ .Release.Name }}-auth"
      port: 8080
      protected: false  # Auth endpoints are public (login, register, etc.)
      middlewares:
        - rate-limit
        - headers
        - compress
  dashboard:
    enabled: false
  # Middleware configurations
  middleware:
    rateLimit:
      enabled: true
      average: 100
      period: 1m
      burst: 50
    headers:
      enabled: true
      stsSeconds: 31536000
      stsIncludeSubdomains: true
      stsPreload: true
      forceSTSHeader: true
      contentTypeNosniff: true
      browserXssFilter: true
      customRequestHeaders:
        X-Forwarded-Proto: https
      customResponseHeaders:
        X-Content-Type-Options: nosniff
        X-Frame-Options: DENY
        X-XSS-Protection: 1; mode=block
    retry:
      enabled: true
      attempts: 3
      initialInterval: 100ms
    circuitBreaker:
      enabled: true
      expression: "NetworkErrorRatio() > 0.30 || ResponseCodeRatio(500, 600, 0, 600) > 0.50"
    compress:
      enabled: true
    basicAuth:
      enabled: false
    cors:
      enabled: true
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      allowHeaders:
        - Content-Type
        - Authorization
        - X-Requested-With
      allowOrigins:
        - "*"
      maxAge: 3600
      addVaryHeader: true
    jwtForwardAuth:
      enabled: false
# Environment variables
