{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgbouncer-secret
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
type: Opaque
stringData:
  # Extract PostgreSQL connection details from DATABASE_URL
  {{- if and .Values.env .Values.env.DATABASE_URL }}
  {{- $dbUrl := .Values.env.DATABASE_URL }}
  {{- if contains "postgresql://" $dbUrl }}
  {{- $withoutProtocol := trimPrefix "postgresql://" $dbUrl }}
  {{- $beforeQuery := index (splitList "?" $withoutProtocol) 0 }}
  {{- $userPass := index (splitList "@" $beforeQuery) 0 }}
  {{- $hostPortDb := index (splitList "@" $beforeQuery) 1 }}
  {{- $user := index (splitList ":" $userPass) 0 }}
  {{- $pass := index (splitList ":" $userPass) 1 }}
  {{- $hostPort := index (splitList "/" $hostPortDb) 0 }}
  {{- $database := index (splitList "/" $hostPortDb) 1 }}
  {{- $host := index (splitList ":" $hostPort) 0 }}
  postgres-user: {{ $user | quote }}
  postgres-password: {{ $pass | quote }}
  postgres-host: {{ $host | quote }}
  postgres-database: {{ $database | quote }}
  {{- else }}
  # Default values when not a PostgreSQL URL
  postgres-user: "postgres"
  postgres-password: "password"
  postgres-host: "postgres"
  postgres-database: "postgres"
  {{- end }}
  {{- else }}
  # Default values when DATABASE_URL is not set
  postgres-user: "postgres"
  postgres-password: "password"
  postgres-host: "postgres"
  postgres-database: "postgres"
  {{- end }}
  # Generate userlist.txt for PgBouncer authentication
  userlist.txt: |
    {{- if and .Values.env .Values.env.DATABASE_URL }}
    {{- $dbUrl := .Values.env.DATABASE_URL }}
    {{- if contains "postgresql://" $dbUrl }}
    {{- $parsed := regexSplit "[@:/]+" (trimPrefix "postgresql://" $dbUrl) -1 }}
    {{- if ge (len $parsed) 2 }}
    # Main database user
    "{{ index $parsed 0 }}" "md5{{ index $parsed 1 | sha256sum | trunc 32 }}"
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if and .Values.env .Values.env.DATABASE_URL_READONLY }}
    {{- $dbUrlReadonly := .Values.env.DATABASE_URL_READONLY }}
    {{- if contains "postgresql://" $dbUrlReadonly }}
    {{- $parsedReadonly := regexSplit "[@:/]+" (trimPrefix "postgresql://" $dbUrlReadonly) -1 }}
    {{- if ge (len $parsedReadonly) 2 }}
    # Read-only database user
    "{{ index $parsedReadonly 0 }}" "md5{{ index $parsedReadonly 1 | sha256sum | trunc 32 }}"
    {{- end }}
    {{- end }}
    {{- end }}
    # PgBouncer admin user
    "pgbouncer" "md5{{ printf "%s%s" "pgbouncer" "admin123" | sha256sum | trunc 32 }}"
{{- end }}