{{- if .Values.pgbouncer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pgbouncer-secret
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgbouncer
type: Opaque
stringData:
  # Use individual database configuration variables
  {{- if .Values.env.DATABASE_HOST }}
  postgres-host: {{ .Values.env.DATABASE_HOST | quote }}
  {{- else }}
  postgres-host: "postgres"
  {{- end }}
  {{- if .Values.env.DATABASE_PORT }}
  postgres-port: {{ .Values.env.DATABASE_PORT | quote }}
  {{- else }}
  postgres-port: "5432"
  {{- end }}
  {{- if .Values.env.DATABASE_NAME }}
  postgres-database: {{ .Values.env.DATABASE_NAME | quote }}
  {{- else }}
  postgres-database: "postgres"
  {{- end }}
  {{- if .Values.env.DATABASE_USER }}
  postgres-user: {{ .Values.env.DATABASE_USER | quote }}
  {{- else }}
  postgres-user: "postgres"
  {{- end }}
  {{- if .Values.env.DATABASE_PASSWORD }}
  postgres-password: {{ .Values.env.DATABASE_PASSWORD | quote }}
  {{- else }}
  postgres-password: "password"
  {{- end }}
  # Generate userlist.txt for PgBouncer authentication
  userlist.txt: |
    {{- if and .Values.env.DATABASE_USER .Values.env.DATABASE_PASSWORD }}
    # Main database user
    "{{ .Values.env.DATABASE_USER }}" "md5{{ printf "%s%s" .Values.env.DATABASE_PASSWORD .Values.env.DATABASE_USER | sha256sum | trunc 32 }}"
    {{- end }}
    # PgBouncer admin user
    "pgbouncer" "md5{{ printf "%s%s" "admin123" "pgbouncer" | sha256sum | trunc 32 }}"
{{- end }}