apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- if or (contains "SECRET" $key) (contains "CERT" $key) (contains "PASSWORD" $key) (eq "DATABASE_URL" $key) }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.env.DATABASE_URL }}
    {{- $url := . | trimPrefix "postgresql://" }}
    {{- $userPass := split "@" $url | first }}
    {{- $hostPortDB := split "@" $url | last }}
    {{- $user := split ":" $userPass | first }}
    {{- $pass := split ":" $userPass | last }}
    {{- $hostPort := split "/" $hostPortDB | first }}
    {{- $host := split ":" $hostPort | first }}
    {{- $port := split ":" $hostPort | last }}
    {{- $db := split "?" (split "/" $hostPortDB | last) | first }}
    POSTGRES_HOST: {{ $host | b64enc | quote }}
    POSTGRES_PORT: {{ $port | b64enc | quote }}
    POSTGRES_USER: {{ $user | b64enc | quote }}
    POSTGRES_PASSWORD: {{ $pass | b64enc | quote }}
    POSTGRES_DB: {{ $db | b64enc | quote }}
  {{- end }}