{{- if .Values.commandCenter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvpipe.fullname" . }}-command-center
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: command-center
spec:
  replicas: {{ .Values.commandCenter.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: command-center
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: command-center
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: command-center
          image: "{{ .Values.commandCenter.image.repository }}:{{ .Values.commandCenter.image.tag }}"
          imagePullPolicy: {{ .Values.commandCenter.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.commandCenter.containerPort | default 3000 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-common-env
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: PORT
              value: {{ .Values.commandCenter.containerPort | default 3000 | quote }}
            - name: GIN_MODE
              value: {{ .Values.commandCenter.env.GIN_MODE | default "release" | quote }}
            {{- if .Values.commandCenter.persistence.enabled }}
            - name: SQLITE_PATH
              value: "/data/audit.db"
            {{- end }}
            {{- if .Values.commandCenter.useReadOnlyDatabase }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL_READONLY
            {{- end }}
            {{- range $key, $value := .Values.commandCenter.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.commandCenter.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
          {{- if .Values.commandCenter.resources }}
          resources:
            {{- toYaml .Values.commandCenter.resources | nindent 12 }}
          {{- end }}
      {{- if .Values.commandCenter.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "pvpipe.fullname" . }}-command-center-pvc
      {{- end }}
{{- end }}