{{- if .Values.commandCenter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvpipe.fullname" . }}-command-center
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: command-center
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.commandCenter.servicePort | default 3000 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pvpipe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: command-center
{{- end }}