{{- if and .Values.msFiles.enabled .Values.msFiles.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-files-worker
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-files-worker
spec:
  replicas: {{ .Values.msFiles.worker.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ms-files-worker
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ms-files-worker
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: ms-files-worker
          image: "{{ .Values.msFiles.worker.image.repository }}:{{ .Values.msFiles.worker.image.tag }}"
          imagePullPolicy: {{ .Values.msFiles.worker.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-common-env
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            {{- if .Values.msFiles.worker.useReadOnlyDatabase }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret
                  key: DATABASE_URL_READONLY
            {{- end }}
            {{- range $key, $value := .Values.msFiles.worker.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.msFiles.worker.resources }}
          resources:
            {{- toYaml .Values.msFiles.worker.resources | nindent 12 }}
          {{- end }}
{{- end }}