{{- if .Values.msMigration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-migration-{{ .Values.msMigration.jobSuffix | default (now | date "20060102150405") }}
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-migration
  annotations:
    "helm.sh/hook": {{ .Values.msMigration.helmHook | default "post-install,post-upgrade" }}
    "helm.sh/hook-weight": {{ .Values.msMigration.hookWeight | default "-5" | quote }}
    "helm.sh/hook-delete-policy": {{ .Values.msMigration.hookDeletePolicy | default "before-hook-creation,hook-succeeded" }}
spec:
  backoffLimit: {{ .Values.msMigration.backoffLimit | default 3 }}
  activeDeadlineSeconds: {{ .Values.msMigration.activeDeadlineSeconds | default 300 }}
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ms-migration
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: {{ .Chart.Name }}-ms-migration
          image: "{{ .Values.msMigration.image.repository }}:{{ .Values.msMigration.image.tag }}"
          imagePullPolicy: {{ .Values.msMigration.image.pullPolicy }}
          command: ["./migrate", "up"]
          envFrom:
            - configMapRef:
                name: {{ include "pvpipe.fullname" . }}-common-env
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: MIGRATIONS_PATH
              value: "{{ .Values.msMigration.migrationsPath }}"
            - name: MIGRATION_TABLE
              value: "{{ .Values.msMigration.migrationTable }}"
            - name: ENVIRONMENT
              value: "{{ .Values.msMigration.environment }}"
            - name: MAX_RETRIES
              value: "{{ .Values.msMigration.maxRetries }}"
            - name: RETRY_DELAY_SECONDS
              value: "{{ .Values.msMigration.retryDelaySeconds }}"
            {{- range $key, $value := .Values.msMigration.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.msMigration.resources | nindent 12 }}
{{- end }}