{{- if .Values.meilisearch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvpipe.fullname" . }}-meilisearch
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: meilisearch
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: "{{ .Values.meilisearch.image.repository }}:{{ .Values.meilisearch.image.tag }}"
        imagePullPolicy: {{ .Values.meilisearch.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 7700
          protocol: TCP
        env:
        - name: MEILI_ENV
          value: {{ .Values.meilisearch.environment | default "production" }}
        {{- if .Values.meilisearch.masterKey }}
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "pvpipe.fullname" . }}-secret
              key: meilisearch-master-key
        {{- end }}
        {{- if .Values.meilisearch.dbPath }}
        - name: MEILI_DB_PATH
          value: {{ .Values.meilisearch.dbPath }}
        {{- end }}
        {{- if .Values.meilisearch.persistence.enabled }}
        volumeMounts:
        - name: meilisearch-data
          mountPath: {{ .Values.meilisearch.persistence.mountPath | default "/meili_data" }}
        {{- end }}
        resources:
          {{- toYaml .Values.meilisearch.resources | nindent 10 }}
      {{- if .Values.meilisearch.persistence.enabled }}
      volumes:
      - name: meilisearch-data
        persistentVolumeClaim:
          claimName: {{ include "pvpipe.fullname" . }}-meilisearch-pvc
      {{- end }}
---
{{- if .Values.meilisearch.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvpipe.fullname" . }}-meilisearch-pvc
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: meilisearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.meilisearch.persistence.size | default "10Gi" }}
  {{- if .Values.meilisearch.persistence.storageClass }}
  storageClassName: {{ .Values.meilisearch.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}