{{- if and .Values.traefik.enabled .Values.services.corsHandler.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvpipe.fullname" . }}-cors-handler
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.services.corsHandler.port | default 8080 }}
    targetPort: {{ .Values.services.corsHandler.port | default 8080 }}
    protocol: TCP
    name: http
  selector:
    {{- include "pvpipe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cors-handler
{{- end }}