{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- range $key, $value := .Values.env }}
  {{- if not (or (contains "SECRET" $key) (contains "CERT" $key) (contains "PASSWORD" $key) (contains "_KEY" $key) (contains "DATABASE" $key)) }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
  {{- end }}
{{- end }}