{{- if .Values.msProject.enabled }}
{{- if .Values.traefik.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-project-routes
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-project-routes
spec:
  entryPoints:
    - web
    {{- if .Values.traefik.tls.enabled }}
    - websecure
    {{- end }}
  routes:
    # Projects API endpoint (plural - correct path)
    - match: PathPrefix(`/api/v1/projects`) && !Method(`OPTIONS`)
      kind: Rule
      priority: 100
      services:
        - name: {{ include "pvpipe.fullname" . }}-ms-project
          port: {{ .Values.msProject.servicePort | default 8080 }}
      middlewares:
        {{- if .Values.traefik.middleware.forwardAuth.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-forward-auth
        {{- end }}
        - name: {{ include "pvpipe.fullname" . }}-rate-limit
        - name: {{ include "pvpipe.fullname" . }}-headers
        - name: {{ include "pvpipe.fullname" . }}-retry
        - name: {{ include "pvpipe.fullname" . }}-compress
        {{- if .Values.traefik.middleware.cors.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-cors
        {{- end }}

    # Tasks API endpoint
    - match: PathPrefix(`/api/v1/tasks`) && !Method(`OPTIONS`)
      kind: Rule
      priority: 100
      services:
        - name: {{ include "pvpipe.fullname" . }}-ms-project
          port: {{ .Values.msProject.servicePort | default 8080 }}
      middlewares:
        {{- if .Values.traefik.middleware.forwardAuth.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-forward-auth
        {{- end }}
        - name: {{ include "pvpipe.fullname" . }}-rate-limit
        - name: {{ include "pvpipe.fullname" . }}-headers
        - name: {{ include "pvpipe.fullname" . }}-retry
        - name: {{ include "pvpipe.fullname" . }}-compress
        {{- if .Values.traefik.middleware.cors.enabled }}
        - name: {{ include "pvpipe.fullname" . }}-cors
        {{- end }}

  {{- if .Values.traefik.tls.enabled }}
  tls:
    {{- if .Values.traefik.tls.secretName }}
    secretName: {{ .Values.traefik.tls.secretName }}
    {{- end }}
    {{- if .Values.traefik.tls.domains }}
    domains:
      {{- toYaml .Values.traefik.tls.domains | nindent 6 }}
    {{- end }}
    {{- if .Values.traefik.tls.options }}
    options:
      name: {{ .Values.traefik.tls.options }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}