{{- if .Values.msToan.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pvpipe.fullname" . }}-ms-toan
  labels:
    {{- include "pvpipe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ms-toan
spec:
  replicas: {{ .Values.msToan.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "pvpipe.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ms-toan
  template:
    metadata:
      labels:
        {{- include "pvpipe.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ms-toan
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      containers:
        - name: ms-toan
          image: "{{ .Values.msToan.image.repository }}:{{ .Values.msToan.image.tag }}"
          imagePullPolicy: {{ .Values.msToan.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.msToan.containerPort | default 8080 }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.msToan.env.ASPNETCORE_ENVIRONMENT | default "Production" | quote }}
            - name: ASPNETCORE_URLS
              value: "http://+:{{ .Values.msToan.containerPort | default 8080 }}"
            {{- range $key, $value := .Values.msToan.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.msToan.resources }}
          resources:
            {{- toYaml .Values.msToan.resources | nindent 12 }}
          {{- end }}
{{- end }}